config/routes.rb
Rails.application.routes.draw do
  get 'question/index'
  root 'questions#index'

resources :users do
  resources :questions
    resources :answers
end

end

app/models/answer.rb
class Answer < ApplicationRecord
  validates :answer, presence: true
  belongs_to :question
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers
  belongs_to :user
  validates :question_title, presence: true,
                    length: { minimum: 5 }

end

app/models/user.rb
class User < ApplicationRecord
  has_many :questions
  has_many :answers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end

  def edit
    @question = Question.find(params[:id])
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to @question
    else
      render 'new'
    end
  end

  def update
    @question = Question.find(params[:id])

    if @question.update(question_params)
      redirect_to @question
    else
      render 'edit'
    end
  end

def destroy
  @question = Question.find(params[:id])
  @question.destroy

  redirect_to questions_path
end

private
  def question_params
    params.require(:question).permit(:question_title, :question_details)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = User.find

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password_hash)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StackOverflow</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/_form.erb
<%= form_with scope: @question, url: questions_path, local: true do |form| %>

<% if @question.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@question.errors.count, "error") %> prohibited
        this question from being saved:
      </h2>
      <ul>
        <% @question.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<p>
  <%= form.label :question_title %><br>
  <%= form.text_field :question_title %>
</p>

<p>
  <%= form.label :question_details %><br>
  <%= form.text_area :question_details %>
</p>

<p>
  <%= form.submit %>
</p>
<% end %>

app/views/questions/edit.html.erb
<h1>Edit question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1> All Questions </h1>

<table>
  <tr>
    <th>Question Title</th>
    <th>|</th>
    <th>More Details</th>
  </tr>

  <% @questions.each do |question| %>
    <tr>
      <td><%= question.question_title %></td>
      <td><%= "" %> </td>
      <td><%= question.question_details %></td>
      <td><%= link_to 'Show', question_path(question) %></td>
       <td><%= link_to 'Edit', edit_question_path(question) %></td>
       <td><%= link_to 'Delete', question_path(question),
                      method: :delete,
                      data: { confirm: "Are you sure you want to delete this post?"} %></td>
    </tr>
  <% end %>
</table>
<br></br>

app/views/questions/new.html.erb
<h1>New Question</h1>



<%= render 'form' %>





<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p>
  <strong>Question:</strong>
  <%= @question.question_title %>
</p>

<p>
  <strong>More details:</strong>
  <%= @question.question_details %>
</p>

<%= link_to 'Back', questions_path %>
<%= link_to 'Edit', edit_question_path(@question) %>
<%= link_to 'Delete', question_path(@question),
                      method: :delete,
                      data: { confirm: "Are you sure you want to delete this post?"} %>

app/views/users/index.html.erb
<h1> Login here </h1>

<%= form_with scope: @user, url: users_path, local: true do |form| %>

<p>
  <%= form.label :email %><br>
  <%= form.text_field :email %>
</p>

<p>
  <%= form.label :password %><br>
  <%= form.password_field :password %>
</p>

<p>
  <%= form.submit %>
</p>
<% end %>

app/views/users/new.html.erb
<h1> Register here </h1>

<%= form_with scope: @user, url: users_path, local: true do |form| %>

<% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<p>
  <%= form.label :first_name %><br>
  <%= form.text_field :first_name %>
</p>

<p>
  <%= form.label :last_name %><br>
  <%= form.text_field :last_name %>
</p>

<p>
  <%= form.label :email %><br>
  <%= form.text_field :email %>
</p>

<p>
  <%= form.label :password %><br>
  <%= form.password_field :password %>
</p>

<p>
  <%= form.submit %>
</p>
<% end %>